### ISSUE TITLE
Feature request: ability to edit more field

### ISSUE THREAD

**Issue by ylxb2016** [alexpdev/torrentfileQt#56]
Hi, alexpdev.

It's an awesome tool which you create! 

Generally, we can edit those 8 fields with torrentfileQt:
![image](https://user-images.githubusercontent.com/23169439/160140379-56410d59-6dc1-4666-9c64-eece86b3f06d.png)

but it's far from enough, it would be great if torrentfileQt could edit **every field**, like Bencode Editor or [torrent-file-editor](https://github.com/torrent-file-editor/torrent-file-editor), including to create/delete/order/search/replace values.

For example:

![image](https://user-images.githubusercontent.com/23169439/160141449-1e04f7a1-3078-4000-87e1-fde592f5117f.png)

Thanks your effort! 👍 ❤️

**Comment by alexpdev** [comment]
Thanks for the feedback!  I will add it to the TODO list

**Comment by ylxb2016** [comment]
Thanks! 
Also it would be perfect if we can edit torrent via dragging and dropping torrent on it. 👍

**Comment by alexpdev** [comment]
I have opened a new branch to work on this issue and have already started making headway.

One of the issues I have, which is why the current editor is so limited, is that there are only a couple of values that you can edit without making the torrent file invalid.  Any manipulations to piece size, file paths, file sizes, the ordering of the files, or the piece hashes themselves would render the entire file invalid.

I'm curious what purpose you might have for editing any of those fields?

**Comment by ylxb2016** [comment]
wow, thanks your quick response! ❤️ 

Lol, about the purpose for editing any of those fields, it's common when you upload/cross-seed at various trackers.

They may have different requirements, so you have to edit/modefy the torrents to meet their demand, otherwise, you need to hash a new torrent, which is a really time comsuming  and disk hurting stuff when your PC are runing a lot of services.

**Comment by alexpdev** [comment]
So I haven't finished the bencode editor, that part might take a while, but I have made significant updates to the current torrent editor tab, and implemented the Drag and Drop feature as well.   Hopefully this will do for now.

**Comment by ylxb2016** [comment]
Great! It works. 👍

**Comment by alexpdev** [comment]
Great... Ive already found a few bugs here and there so check back once in while to for updates.  And if you find one yourself feel free to open another issue.

Thanks
